# Generated by Django 3.2.1 on 2023-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='ExerciseOrBreak',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
        migrations.AddField(
            model_name='entry',
            name='TimeForExercise',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
