# Generated by Django 3.2.1 on 2023-08-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_rename_exerciseorbreak_entry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='TimeForExercise',
            new_name='content',
        ),
    ]
