# Generated by Django 3.2.1 on 2023-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_rename_timeforexercise_entry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='seconds',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
