# Generated by Django 3.2.1 on 2023-08-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='seconds',
        ),
    ]
