# Generated by Django 3.2.1 on 2023-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20230821_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='minutes',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
