# Generated by Django 3.2.1 on 2023-08-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_remove_entry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='order_in_workout',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='order_in_workout',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
