# Generated by Django 3.2.1 on 2023-08-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20230824_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='workout',
            new_name='exercise',
        ),
    ]
