# Generated by Django 3.2.1 on 2023-08-30 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_rename_workout_entry_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order_in_workout',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='seconds',
            field=models.IntegerField(),
        ),
    ]
