# Generated by Django 3.2.1 on 2023-08-30 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20230830_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order_in_workout',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
