# Generated by Django 3.2.1 on 2023-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_alter_entry_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='exercise',
            field=models.CharField(max_length=40),
        ),
    ]
